spring:
  datasource:
    druid:
      mysql-datasource:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/mysqldb?characterEncoding=UTF-8&useUnicode=true
        username: root
        password: passwd

      sqlserver-datasource:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
        url: jdbc:sqlserver://localhost:1433;DatabaseName=SQLSERVERDB
        username: sa
        password: passwd

thread:
  pool:
    core-pool-size: 10
    max-pool-sie: 10
    keep-alive-second: 60
    queue-size: 100